-- Rewards program update for Supabase PostgreSQL
-- Run in Supabase SQL Editor if you want the same rewards rules stored in Postgres.

create table if not exists public.rewards_settings (
    setting_id bigint generated by default as identity primary key,
    setting_key text not null unique,
    setting_value text not null,
    updated_at timestamptz not null default now()
);

alter table if exists public.user_rewards
    add column if not exists redeemed_points integer not null default 0,
    add column if not exists tier text not null default 'Bronze',
    add column if not exists updated_at timestamptz not null default now();

create table if not exists public.reward_transactions (
    tx_id bigint generated by default as identity primary key,
    user_id bigint not null,
    points integer not null default 0,
    type text not null default 'earned',
    description text,
    created_at timestamptz not null default now()
);

create index if not exists reward_transactions_user_id_idx on public.reward_transactions(user_id);

insert into public.rewards_settings (setting_key, setting_value)
values
    ('purchase_11kg_points', '100'),
    ('refill_11kg_points', '60'),
    ('purchase_22kg_points', '180'),
    ('refill_22kg_points', '120'),
    ('bronze_bonus_pct', '0'),
    ('silver_bonus_pct', '10'),
    ('gold_bonus_pct', '20'),
    ('platinum_bonus_pct', '30'),
    ('silver_threshold', '5'),
    ('gold_threshold', '15'),
    ('platinum_threshold', '30'),
    ('redemption_rate', '500'),
    ('redemption_value', '50'),
    ('points_enabled', '1')
on conflict (setting_key) do update
set setting_value = excluded.setting_value,
    updated_at = now();
